### PR TITLE
Lockdown the email domain

### PR DESCRIPTION
**Pull request by mlttanaka**
Add the coaches'  email domain to env variable EMAIL_DOMAIN to tighten up access.

### CODE REVIEW

**Comment by Brit200313** [comment]
@mlttanaka would you (please) be able to adjust the tests so they will pass? I'm guessing the restricted domain is stopping it. Also, I haven't deployed a staging site since we moved to Heroku.

**Comment by mlttanaka** [comment]
Odd... The test are passing locally here. I can set up a staging server on Heroku.

**Comment by mlttanaka** [comment]
Staging server up and happy & Codeship is reconfigured and happy.  WOOT.

**Comment by Brit200313** [comment]
yay! well done!

**Pull request merged**
